vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    VehiclesImage:
      uri_prefix: /assets/img_uploads/vehicles/
      upload_destination: "%kernel.project_dir%/public/assets/img_uploads/vehicles/"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    ServicesImage:
      uri_prefix: /assets/img_uploads/services/
      upload_destination: "%kernel.project_dir%/public/assets/img_uploads/services/"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
