vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    Image:
      uri_prefix: /assets/img_uploads/
      upload_destination: "%kernel.project_dir%/public/assets/img_uploads/"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
