<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerENMy62C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerENMy62C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerENMy62C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerENMy62C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerENMy62C\App_KernelDevDebugContainer([
    'container.build_hash' => 'ENMy62C',
    'container.build_id' => 'bb5e7ade',
    'container.build_time' => 1696866824,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerENMy62C');
