<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWpt5JP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWpt5JP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWpt5JP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWpt5JP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAWpt5JP\App_KernelDevDebugContainer([
    'container.build_hash' => 'AWpt5JP',
    'container.build_id' => '4d0990af',
    'container.build_time' => 1699975438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWpt5JP');
