<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ee7RRx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ee7RRx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8ee7RRx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8ee7RRx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8ee7RRx\App_KernelDevDebugContainer([
    'container.build_hash' => '8ee7RRx',
    'container.build_id' => 'd9a2e509',
    'container.build_time' => 1694625543,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ee7RRx');
